### PR TITLE
Collection sensitivity has been added

### PR DESCRIPTION
**Pull request by BorisKotlyarov**

### CODE REVIEW

**Comment by BorisKotlyarov** [comment]
Preview
screenshot

**Comment by freshstudio** [comment]
I don't really understand what's the point in it.
Can you explain why do we need it?

**Comment by kaffem** [comment]
I guess something with collecting range, not sure...

**Comment by BorisKotlyarov** [comment]
The bot is too good for collecting boxes, P.E.T. does not get anything, and it's a failure, because it has the opportunity to increase the amount of profit due to the "Salvage protocol X"
3%x12 = 36%

**Comment by freshstudio** [comment]
I can merge, but please change the sensitivity to be always the highest.

**Comment by BorisKotlyarov** [comment]
ok

**Comment by freshstudio** [comment]
Thanks!

**Pull request merged**
