### PR TITLE
Collect boxes while killing npc

### PR DESCRIPTION
**Pull request by lestrox**
I reviewed for 2 days. Thıs works perfectly.

### CODE REVIEW

**Comment by freshstudio** [comment]
1. `box.distance + ship.distance< 550` why?
2. The code looks like a salad now, please use spaces instead of tab.

**Comment by lestrox** [comment]
if you can, do. or you dont do this, please show respect first. this's works perfect for me. 
edited for `box.distance < 700`

**Comment by Mspy1** [comment]
You don't have to be so pretentious.
All of our contributors did great job especially @BorisKotlyarov  @HaselLoyance.
But they have never added a word like this; ```+Collect boxes while killing npc runs together and "perfect". Added by Lestrox on 28.12.2017```

**Comment by freshstudio** [comment]
Can you remove that copyright note and explain why do you use a fixed distance? And why do you add `box.distance + ship.distance`?

**Comment by lestrox** [comment]
this is an open-source project, am i wrong? this team have too much ego, you do not care about anything. I am asking a question about "what's the attackerId?" and your answer is "its the attackerId.". you dont want others to learn and contribute. this is not open-source. i can remove my note but when you turn to the EXE, you just write the name of the original team. they want this function, its easily for you Freshek, just 10 minutes to create new logic. but you don't. please question urself and show respect. i just wanna to see it
i add `box.distance + ship.distance`, because I had 2 find the box distance of the NPC.

**Comment by freshstudio** [comment]
Didn't even read. Too pointless to discuss here.

**Comment by freshstudio** [comment]
Okay, after reading – that's an open-source project and your code is copyrighted by you and there's no need for a copyright note. `attackerId` is the ID of Attacker. What should I explain? Could you simply calm down?

**Pull request closed without merging**
