### PR TITLE
Updated worker.js

### PR DESCRIPTION
**Pull request by alperensert**
I add collect box while killing npc :)

### CODE REVIEW

**Comment by kaffem** [comment]
Is it with a button to disable it? Cant check myself, mobile data

**Comment by alperensert** [comment]
No I don't add button. I will add soon. Thank you for idea

**Comment by Izakun** [comment]
circle around the NPC and in the same time collect the boxes ?

**Comment by freshstudio** [comment]
Please explain your code a bit.

**Pull request closed without merging**
